# This file was generated by @liquid-labs/sdlc-projects-workflow-local-node-build.
# Refer to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-local-
# node-build for further details

SRC:=src
DIST:=dist
TEST_STAGING:=test-staging
QA:=qa
